local c = require('darkplus.palette')

-- Navic
return {
   NavicIconsFile = { link = 'CmpItemKindFile' },
   NavicIconsModule = { link = 'CmpItemKindModule' },
   NavicIconsNamespace = { link = 'CmpItemKindModule' },
   NavicIconsPackage = { link = 'CmpItemKindModule' },
   NavicIconsClass = { link = 'CmpItemKindClass' },
   NavicIconsMethod = { link = 'CmpItemKindMethod' },
   NavicIconsProperty = { link = 'CmpItemKindProperty' },
   NavicIconsField = { link = 'CmpItemKindField' },
   NavicIconsConstructor = { link = 'CmpItemKindConstructor' },
   NavicIconsEnum = { link = 'CmpItemKindEnum' },
   NavicIconsInterface = { link = 'CmpItemKindInterface' },
   NavicIconsFunction = { link = 'CmpItemKindFunction' },
   NavicIconsVariable = { link = 'CmpItemKindVariable' },
   NavicIconsConstant = { link = 'CmpItemKindConstant' },
   NavicIconsString = { link = 'String' },
   NavicIconsNumber = { link = 'Number' },
   NavicIconsBoolean = { link = 'Boolean' },
   NavicIconsArray = { link = 'CmpItemKindClass' },
   NavicIconsObject = { link = 'CmpItemKindClass' },
   NavicIconsKey = { link = 'CmpItemKindKeyword' },
   NavicIconsKeyword = { link = 'CmpItemKindKeyword' },
   NavicIconsNull = { fg = c.blue, bg = nil },
   NavicIconsEnumMember = { link = 'CmpItemKindEnumMember' },
   NavicIconsStruct = { link = 'CmpItemKindStruct' },
   NavicIconsEvent = { link = 'CmpItemKindEvent' },
   NavicIconsOperator = { link = 'CmpItemKindOperator' },
   NavicIconsTypeParameter = { link = 'CmpItemKindTypeParameter' },
   NavicText = { fg = c.gray, bg = nil },
   NavicSeparator = { fg = c.context, bg = nil },
}
