local c = require('darkplus.palette').colors

-- neo-tree
return {
   -- hl(0, "NeoTreeNormal", { link = "Normal" })
   NeoTreeNormal = { fg = c.fg, bg = c.alt_bg },
   -- hl(0, "NeoTreeNormalNC", { link = "NormalNC" })
   NeoTreeNormalNC = { fg = c.fg, bg = c.alt_bg },
   NeoTreeSignColumn = { link = 'SignColumn' },
   NeoTreeStatusLine = { link = 'StatusLine' },
   NeoTreeStatusLineNC = { link = 'StatusLineNC' },
   NeoTreeVertSplit = { link = 'VertSplit' },
   NeoTreeWinSeparator = { link = 'WinSeparator' },
   NeoTreeEndOfBuffer = { link = 'EndOfBuffer' },
   NeoTreeFloatBorder = { link = 'FloatBorder' },
   NeoTreeFloatNormal = { link = 'NormalFloat' },
   NeoTreeFloatTitle = { bold = true, fg = c.blue, bg = c.alt_bg },
   NeoTreeTitleBar = { fg = c.bg, bg = c.gray },
   NeoTreeBufferNumber = { link = 'SpecialChar' },
   NeoTreeDimText = { fg = c.cursor_fg },
   NeoTreeMessage = { italic = true, fg = c.cursor_fg },
   NeoTreeFadeText1 = { fg = c.context },
   NeoTreeFadeText2 = { fg = c.dark_gray },
   NeoTreeDotfile = { fg = c.context },
   NeoTreeHiddenByName = { link = 'NeoTreeDotfile' },
   NeoTreeCursorLine = { link = 'CursorLine' },
   NeoTreeDirectoryName = { link = 'Directory' },
   NeoTreeDirectoryIcon = { link = 'Directory' },
   NeoTreeFileIcon = { link = 'NeoTreeDirectoryIcon' },
   NeoTreeFileName = {}, -- cleared
   NeoTreeFileNameOpened = { bold = true },
   NeoTreeSymbolicLinkTarget = { link = 'NeoTreeFileName' },
   NeoTreeFilterTerm = { link = 'SpecialChar' },
   NeoTreeRootName = { bold = true, italic = true },
   NeoTreeIndentMarker = { link = 'NeoTreeDimText' },
   NeoTreeExpander = { link = 'NeoTreeDimText' },
   NeoTreeModified = { fg = c.yellow },
   NeoTreeWindowsHidden = { link = 'NeoTreeDotfile' },
   NeoTreePreview = { link = 'Search' },
   NeoTreeGitAdded = { link = 'GitSignsAdd' },
   NeoTreeGitDeleted = { link = 'GitSignsDelete' },
   NeoTreeGitModified = { link = 'GitSignsChange' },
   NeoTreeGitConflict = { bold = true, italic = true, fg = c.warn },
   NeoTreeGitIgnored = { link = 'NeoTreeDotfile' },
   NeoTreeGitRenamed = { link = 'NeoTreeGitModified' },
   NeoTreeGitStaged = { link = 'NeoTreeGitAdded' },
   NeoTreeGitUnstaged = { link = 'NeoTreeGitConflict' },
   NeoTreeGitUntracked = { italic = true, fg = c.warn },
   NeoTreeTabActive = { bold = true, fg = c.fg, bg = c.ui_blue },
   NeoTreeTabInactive = { fg = c.gray10, bg = c.gray3 },
   NeoTreeTabSeparatorActive = { fg = c.alt_bg, bg = c.ui_blue },
   NeoTreeTabSeparatorInactive = { fg = c.alt_bg, bg = c.gray3 },
}
