local c = require('darkplus.palette').colors

-- noice
return {
   -- NoiceCmdline = { fg = c.hint, bg = c.hint },
   -- NoiceCmdlineIcon = { fg = c.hint, bg = c.hint },
   -- NoiceCmdlineIconCmdline = { fg = c.hint, bg = c.hint },
   -- NoiceCmdlineIconFilter = { fg = c.hint, bg = c.hint },
   -- NoiceCmdlineIconHelp = { fg = c.hint, bg = c.hint },
   -- NoiceCmdlineIconIncRename = { fg = c.hint, bg = c.hint },
   -- NoiceCmdlineIconInput = { fg = c.hint, bg = c.hint },
   -- NoiceCmdlineIconLua = { fg = c.hint, bg = c.hint },
   -- NoiceCmdlineIconSearch = { fg = c.hint, bg = c.hint },
   -- NoiceCmdlinePopup = { fg = c.hint, bg = c.hint },
   NoiceCmdlinePopupBorder = { fg = c.hint, bg = nil },
   -- NoiceCmdlinePopupBorderCmdline = { fg = c.hint, bg = c.hint },
   -- NoiceCmdlinePopupBorderFilter = { fg = c.hint, bg = c.hint },
   -- NoiceCmdlinePopupBorderHelp = { fg = c.hint, bg = c.hint },
   -- NoiceCmdlinePopupBorderIncRename = { fg = c.hint, bg = c.hint },
   -- NoiceCmdlinePopupBorderInput = { fg = c.hint, bg = c.hint },
   -- NoiceCmdlinePopupBorderLua = { fg = c.hint, bg = c.hint },
   -- NoiceCmdlinePopupBorderSearch = { fg = c.hint, bg = c.hint },
   -- NoiceCmdlinePrompt = { fg = c.hint, bg = c.hint },

   -- NoiceCompletionItemKindClass = { fg = c.hint, bg = c.hint },
   -- NoiceCompletionItemKindColor = { fg = c.hint, bg = c.hint },
   -- NoiceCompletionItemKindConstant = { fg = c.hint, bg = c.hint },
   -- NoiceCompletionItemKindConstructor = { fg = c.hint, bg = c.hint },
   -- NoiceCompletionItemKindDefault = { fg = c.hint, bg = c.hint },
   -- NoiceCompletionItemKindEnum = { fg = c.hint, bg = c.hint },
   -- NoiceCompletionItemKindEnumMember  = { fg = c.hint, bg = c.hint },
   -- NoiceCompletionItemKindField = { fg = c.hint, bg = c.hint },
   -- NoiceCompletionItemKindFile = { fg = c.hint, bg = c.hint },
   -- NoiceCompletionItemKindFolder = { fg = c.hint, bg = c.hint },
   -- NoiceCompletionItemKindFunction = { fg = c.hint, bg = c.hint },
   -- NoiceCompletionItemKindInterface = { fg = c.hint, bg = c.hint },
   -- NoiceCompletionItemKindKeyword = { fg = c.hint, bg = c.hint },
   -- NoiceCompletionItemKindMethod = { fg = c.hint, bg = c.hint },
   -- NoiceCompletionItemKindModule = { fg = c.hint, bg = c.hint },
   -- NoiceCompletionItemKindProperty = { fg = c.hint, bg = c.hint },
   -- NoiceCompletionItemKindSnippet = { fg = c.hint, bg = c.hint },
   -- NoiceCompletionItemKindStruct = { fg = c.hint, bg = c.hint },
   -- NoiceCompletionItemKindText = { fg = c.hint, bg = c.hint },
   -- NoiceCompletionItemKindUnit = { fg = c.hint, bg = c.hint },
   -- NoiceCompletionItemKindValue = { fg = c.hint, bg = c.hint },
   -- NoiceCompletionItemKindVariable = { fg = c.hint, bg = c.hint },
   -- NoiceCompletionItemMenu = { fg = c.hint, bg = c.hint },
   -- NoiceCompletionItemWord = { fg = c.hint, bg = c.hint },

   -- NoiceConfirm = { fg = c.hint, bg = c.hint },
   -- NoiceConfirmBorder = { fg = c.hint, bg = c.hint },
   -- NoiceCursor = { fg = c.hint, bg = c.hint },

   -- NoiceFormatConfirm = { fg = c.hint, bg = c.hint },
   -- NoiceFormatConfirmDefault = { fg = c.hint, bg = c.hint },
   -- NoiceFormatDate = { fg = c.hint, bg = c.hint },
   -- NoiceFormatEvent = { fg = c.hint, bg = c.hint },
   -- NoiceFormatKind = { fg = c.hint, bg = c.hint },
   -- NoiceFormatLevelDebug = { fg = c.hint, bg = c.hint },
   -- NoiceFormatLevelError = { fg = c.hint, bg = c.hint },
   -- NoiceFormatLevelInfo = { fg = c.hint, bg = c.hint },
   -- NoiceFormatLevelOff = { fg = c.hint, bg = c.hint },
   -- NoiceFormatLevelTrace = { fg = c.hint, bg = c.hint },
   -- NoiceFormatLevelWarn = { fg = c.hint, bg = c.hint },
   -- NoiceFormatProgressDone = { fg = c.hint, bg = c.hint },
   -- NoiceFormatProgressTodo = { fg = c.hint, bg = c.hint },
   -- NoiceFormatTitle = { fg = c.hint, bg = c.hint },

   -- NoiceLspProgressClient = { fg = c.hint, bg = c.hint },
   -- NoiceLspProgressSpinner = { fg = c.hint, bg = c.hint },
   -- NoiceLspProgressTitle = { fg = c.hint, bg = c.hint },

   -- NoiceMini = { fg = c.hint, bg = c.hint },
   -- NoicePopup = { fg = c.hint, bg = c.hint },
   -- NoicePopupBorder = { fg = c.hint, bg = c.hint },
   -- NoicePopupmenu = { fg = c.hint, bg = c.hint },
   -- NoicePopupmenuBorder = { fg = c.hint, bg = c.hint },
   -- NoicePopupmenuMatch = { fg = c.hint, bg = c.hint },
   -- NoicePopupmenuSelected = { fg = c.hint, bg = c.hint },
   -- NoiceScrollbar = { fg = c.hint, bg = c.hint },
   -- NoiceScrollbarThumb = { fg = c.hint, bg = c.hint },
   -- NoiceSplit = { fg = c.hint, bg = c.hint },
   -- NoiceSplitBorder = { fg = c.hint, bg = c.hint },
   NoiceVirtualText = { fg = c.hint, bg = c.hint_bg },
}
