local c = require('darkplus.palette').colors

-- Blink.cmp
return {
   -- kind
   BlinkCmpKindFunction = { fg = c.ui_purple, bg = nil },
   BlinkCmpKindMethod = { fg = c.ui_purple, bg = nil },
   BlinkCmpKindConstructor = { fg = c.ui_orange, bg = nil },
   BlinkCmpKindClass = { fg = c.ui_orange, bg = nil },
   BlinkCmpKindEnum = { fg = c.ui_orange, bg = nil },
   BlinkCmpKindEvent = { fg = c.info, bg = nil },
   BlinkCmpKindInterface = { fg = c.ui_orange, bg = nil },
   BlinkCmpKindStruct = { fg = c.ui_orange, bg = nil },
   BlinkCmpKindVariable = { fg = c.light_blue, bg = nil },
   BlinkCmpKindField = { fg = c.light_blue, bg = nil },
   BlinkCmpKindProperty = { fg = c.light_blue, bg = nil },
   BlinkCmpKindEnumMember = { fg = c.vivid_blue, bg = nil },
   BlinkCmpKindConstant = { fg = c.vivid_blue, bg = nil },
   BlinkCmpKindModule = { fg = c.cyan, bg = nil },
   BlinkCmpKindReference = { fg = c.light_blue, bg = nil },
   BlinkCmpKindTypeParameter = { fg = c.light_blue, bg = nil },

   -- Pmenuとかにリンクしてるので基本的には不要。Borderだけ薄くしたかったので下記を設定
   BlinkCmpMenuBorder = { link = 'NormalFloatBorder' },
   BlinkCmpDocBorder = { link = 'NormalFloatBorder' },
   BlinkCmpSignatureHelpBorder = { link = 'NormalFloatBorder' },
   BlinkCmpDocSeparator = { link = 'NormalFloatBorder' },
   BlinkCmpDoc = { fg = c.gray10 }, -- blink-cmp のコード補完の fg が暗いので修正

   -- BlinkCmpKindEnum = { fg = c.gray10 },
   BlinkCmpKindFile = { fg = c.gray10 },
   BlinkCmpKindText = { fg = c.gray10 },
   BlinkCmpKindUnit = { fg = c.gray10 },
   -- BlinkCmpKindClass = { fg = c.gray10 },
   BlinkCmpKindColor = { fg = c.gray10 },
   -- BlinkCmpKindEvent = { fg = c.gray10 },
   -- BlinkCmpKindField = { fg = c.gray10 },
   BlinkCmpKindValue = { fg = c.gray10 },
   BlinkCmpKindFolder = { fg = c.gray10 },
   -- BlinkCmpKindMethod = { fg = c.gray10 },
   -- BlinkCmpKindModule = { fg = c.gray10 },
   -- BlinkCmpKindStruct = { fg = c.gray10 },
   BlinkCmpKindKeyword = { fg = c.gray10 },
   BlinkCmpKindSnippet = { fg = c.gray10 },
   -- BlinkCmpKindConstant = { fg = c.gray10 },
   -- BlinkCmpKindFunction = { fg = c.gray10 },
   BlinkCmpKindOperator = { fg = c.gray10 },
   -- BlinkCmpKindProperty = { fg = c.gray10 },
   -- BlinkCmpKindVariable = { fg = c.gray10 },
   -- BlinkCmpKindInterface = { fg = c.gray10 },
   -- BlinkCmpKindReference = { fg = c.gray10 },
   -- BlinkCmpKindEnumMember = { fg = c.gray10 },
   -- BlinkCmpKindConstructor = { fg = c.gray10 },
   -- BlinkCmpKindTypeParameter = { fg = c.gray10 },
   BlinkCmpKind = { fg = c.gray10 },

   -- PmenuExtra にlink してるのが多いのでそっちの fg を変更
   -- BlinkCmpCursorLineMenuHack = { fg = c.gray10 },
   -- BlinkCmpCursorLineDocumentationHack = { fg = c.gray10 },
   -- -- BlinkCmpGhostText = { fg = c.gray10 },
   -- BlinkCmpDocCursorLine = { fg = c.gray10 },
   -- BlinkCmpSource = { fg = c.gray10 },
   -- BlinkCmpMenuSelection = { fg = c.gray10 },
   -- BlinkCmpLabelDetail = { fg = c.gray10 },
   -- BlinkCmpScrollBarGutter = { fg = c.gray10 },
   -- BlinkCmpScrollBarThumb = { fg = c.gray10 },
   -- BlinkCmpLabelDeprecated = { fg = c.gray10 },
   -- BlinkCmpLabelDescription = { fg = c.gray10 },
   -- BlinkCmpMenu = { fg = c.gray10 },
   -- -- BlinkCmpDocBorder = { fg = c.gray10 },
   -- -- BlinkCmpMenuBorder = { fg = c.gray10 },
   -- -- BlinkCmpDocSeparator = { fg = c.gray10 },
   -- -- BlinkCmpSignatureHelpBorder = { fg = c.gray10 },
   -- BlinkCmpSignatureHelp = { fg = c.gray10 },
   -- BlinkCmpSignatureHelpActiveParameter = { fg = c.gray10 },
}
