local c = require('darkplus.palette').colors

-- cmp
return {
   CmpItemAbbrDeprecated = { fg = c.gray, bg = nil, strikethrough = true },
   CmpItemAbbrMatch = { fg = c.ui3_blue, bg = nil },
   CmpItemAbbrMatchFuzzy = { fg = c.ui3_blue, bg = nil },
   CmpItemKindFunction = { fg = c.ui_purple, bg = nil },
   CmpItemKindMethod = { fg = c.ui_purple, bg = nil },
   CmpItemKindConstructor = { fg = c.ui_orange, bg = nil },
   CmpItemKindClass = { fg = c.ui_orange, bg = nil },
   CmpItemKindEnum = { fg = c.ui_orange, bg = nil },
   CmpItemKindEvent = { fg = c.info, bg = nil },
   CmpItemKindInterface = { fg = c.ui_orange, bg = nil },
   CmpItemKindStruct = { fg = c.ui_orange, bg = nil },
   CmpItemKindVariable = { fg = c.light_blue, bg = nil },
   CmpItemKindField = { fg = c.light_blue, bg = nil },
   CmpItemKindProperty = { fg = c.light_blue, bg = nil },
   CmpItemKindEnumMember = { fg = c.vivid_blue, bg = nil },
   CmpItemKindConstant = { fg = c.vivid_blue, bg = nil },
   CmpItemKindKeyword = { fg = c.fg, bg = nil },
   CmpItemKindModule = { fg = c.cyan, bg = nil },
   CmpItemKindValue = { fg = c.fg, bg = nil },
   CmpItemKindUnit = { fg = c.fg, bg = nil },
   CmpItemKindText = { fg = c.fg, bg = nil },
   CmpItemKindSnippet = { fg = c.fg, bg = nil },
   CmpItemKindFile = { fg = c.fg, bg = nil },
   CmpItemKindFolder = { fg = c.fg, bg = nil },
   CmpItemKindColor = { fg = c.fg, bg = nil },
   CmpItemKindReference = { fg = c.light_blue, bg = nil },
   CmpItemKindOperator = { fg = c.fg, bg = nil },
   CmpItemKindTypeParameter = { fg = c.light_blue, bg = nil },
   CmpItemMenuDefault = { fg = c.dark_gray },
   CmpNormal = { link = 'Pmenu' },
   CmpFloatBorder = { fg = c.dark_gray },
   CmpCursorLine = { fg = nil, bg = c.ui_blue },
   CmpSearch = { link = nil },
}
