local c = require('darkplus.palette')

-- Code
return {
   Comment = { fg = c.green, bg = nil },
   Variable = { fg = c.light_blue, bg = nil },
   String = { fg = c.orange, bg = nil },
   Character = { fg = c.orange, bg = nil },
   Number = { fg = c.light_green, bg = nil },
   Float = { fg = c.light_green, bg = nil },
   Boolean = { fg = c.blue, bg = nil },
   Constant = { fg = c.vivid_blue, bg = nil },
   Type = { fg = c.cyan, bg = nil },
   Function = { fg = c.yellow, bg = nil },
   Keyword = { fg = c.blue, bg = nil },
   Conditional = { fg = c.purple, bg = nil },
   Repeat = { fg = c.purple, bg = nil },
   Operator = { fg = c.fg, bg = nil },
   PreProc = { fg = c.purple, bg = nil },
   Include = { fg = c.purple, bg = nil },
   Exception = { fg = c.purple, bg = nil },
   StorageClass = { fg = c.cyan, bg = nil },
   Structure = { fg = c.cyan, bg = nil },
   Typedef = { fg = c.purple, bg = nil },
   Define = { fg = c.purple, bg = nil },
   Macro = { fg = c.purple, bg = nil },
   Debug = { fg = c.red, bg = nil },
   Title = { fg = c.blue, bg = nil, bold = true },
   Label = { fg = c.blue, bg = nil },
   SpecialChar = { fg = c.yellow_orange, bg = nil },
   Delimiter = { fg = c.fg, bg = nil },
   SpecialComment = { fg = c.fg, bg = nil },
   Tag = { fg = c.blue, bg = nil },
   Bold = { fg = nil, bg = nil, bold = true },
   Italic = { fg = nil, bg = nil, italic = true },
   Underlined = { fg = nil, bg = nil, underline = true },
   Ignore = { fg = c.magenta, bg = nil, bold = true },
   Todo = { fg = c.magenta, bg = nil, bold = true },
   Error = { fg = c.error, bg = nil, bold = true },
   Statement = { fg = c.purple, bg = nil },
   Identifier = { fg = c.light_blue, bg = nil },
   PreCondit = { fg = c.purple, bg = nil },
   Special = { fg = c.orange, bg = nil },
}
