local c = require('darkplus.palette').colors

return {
   -- General
   Normal = { fg = c.fg, bg = c.bg },
   SignColumn = { fg = nil, bg = nil },
   MsgArea = { fg = c.fg, bg = c.bg },
   ModeMsg = { fg = c.fg, bg = c.alt_bg },
   MsgSeparator = { fg = c.fg, bg = c.bg },
   NormalNC = { fg = c.fg, bg = c.bg },
   LineNr = { fg = c.gray, bg = nil },
   CursorLineNr = { fg = c.light_gray, bg = nil },
   Folded = { fg = c.gray, bg = c.alt_bg },
   FoldColumn = { fg = c.gray, bg = c.alt_bg },
   Whitespace = { fg = c.dark_gray, bg = nil },
   VertSplit = { fg = c.gray, bg = c.bg },
   ColorColumn = { fg = nil, bg = c.alt_bg },
   Conceal = { fg = c.gray, bg = nil },
   Directory = { fg = c.folder_blue, bg = nil },
   SpecialKey = { fg = c.blue, bg = nil, bold = true },
   EndOfBuffer = { fg = c.bg, bg = nil },
   NonText = { fg = c.gray8, bg = nil },

   -- Cursor
   Cursor = { fg = c.cursor_fg, bg = c.cursor_bg },
   lCursor = { fg = c.cursor_fg, bg = c.cursor_bg },
   CursorIM = { fg = c.cursor_fg, bg = c.cursor_bg },
   TermCursor = { fg = c.cursor_fg, bg = c.cursor_bg },
   TermCursorNC = { fg = c.cursor_fg, bg = c.cursor_bg },
   CursorLine = { fg = nil, bg = c.alt_bg },
   CursorColumn = { fg = nil, bg = c.alt_bg },

   -- Mode
   Visual = { fg = nil, bg = c.ui_blue },
   VisualNOS = { fg = nil, bg = c.alt_bg },

   -- Msg / Comment / Diagnostic
   Comment = { fg = c.green, bg = nil },
   SpecialComment = { fg = c.fg, bg = nil },
   Todo = { fg = c.magenta, bg = nil, bold = true },
   Debug = { fg = c.red, bg = nil },
   Error = { fg = c.error, bg = nil, bold = true },
   Ignore = { fg = c.magenta, bg = nil, bold = true },

   -- Search
   Search = { fg = nil, bg = c.ui5_blue },
   IncSearch = { fg = nil, bg = c.ui2_orange },
   Substitute = { fg = nil, bg = c.ui2_orange },

   -- Match
   MatchWord = { fg = nil, bg = c.reference },
   MatchParen = { fg = c.hint, bg = c.reference },
   MatchWordCur = { fg = nil, bg = c.reference },
   MatchParenCur = { fg = nil, bg = c.reference },

   -- Message
   ErrorMsg = { fg = c.error, bg = c.bg, bold = true },
   WarningMsg = { fg = c.ui_orange, bg = c.bg },
   MoreMsg = { fg = c.orange, bg = nil },
   Question = { fg = c.orange, bg = nil },

   -- Spell
   SpellBad = { fg = nil, bg = nil, sp = c.red, undercurl = true },
   SpellCap = { fg = nil, bg = nil, sp = c.yellow, undercurl = true },
   SpellLocal = { fg = nil, bg = nil, sp = c.green, underline = true },
   SpellRare = { fg = nil, bg = nil, sp = c.purple, underline = true },

   -- Diff
   DiffText = { bg = c.sign_delete_bg },
   DiffAdd = { bg = c.sign_add_bg },
   DiffChange = { bg = c.sign_change_bg },
   DiffDelete = { bg = c.sign_delete_bg },

   -- Symbols
   SymbolsOutlineConnector = { fg = c.gray, bg = nil },
   FocusedSymbol = { fg = nil, bg = '#36383F' },

   -- Syntax / Code
   Variable = { fg = c.light_blue, bg = nil },
   Identifier = { fg = c.light_blue, bg = nil },
   Constant = { fg = c.vivid_blue, bg = nil },
   String = { fg = c.orange, bg = nil },
   Character = { fg = c.orange, bg = nil },
   Number = { fg = c.light_green, bg = nil },
   Float = { fg = c.light_green, bg = nil },
   Boolean = { fg = c.blue, bg = nil },
   Type = { fg = c.cyan, bg = nil },
   StorageClass = { fg = c.cyan, bg = nil },
   Structure = { fg = c.cyan, bg = nil },
   Typedef = { fg = c.purple, bg = nil },

   -- Function / Declaration
   Function = { fg = c.yellow, bg = nil },

   -- Keyword / Statement
   Keyword = { fg = c.blue, bg = nil },
   Conditional = { fg = c.purple, bg = nil },
   Repeat = { fg = c.purple, bg = nil },
   Statement = { fg = c.purple, bg = nil },
   Operator = { fg = c.fg, bg = nil },
   Label = { fg = c.blue, bg = nil },
   Exception = { fg = c.purple, bg = nil },
   Define = { fg = c.purple, bg = nil },
   Macro = { fg = c.purple, bg = nil },
   PreProc = { fg = c.purple, bg = nil },
   PreCondit = { fg = c.purple, bg = nil },
   Include = { fg = c.purple, bg = nil },

   -- Special / Symbol
   Special = { fg = c.orange, bg = nil },
   SpecialChar = { fg = c.yellow_orange, bg = nil },
   Delimiter = { fg = c.fg, bg = nil },
   Tag = { fg = c.blue, bg = nil },

   -- UI / Title / Style
   Title = { fg = c.blue, bg = nil, bold = true },
   Bold = { fg = nil, bg = nil, bold = true },
   Italic = { fg = nil, bg = nil, italic = true },
   Underlined = { fg = nil, bg = nil, underline = true },

   -- Tab
   TabLine = { fg = c.light_gray, bg = c.line },
   TabLineSel = { fg = c.fg, bg = c.line },
   TabLineFill = { fg = c.line, bg = c.line },

   -- Win
   WinBar = { bg = c.bg },
   WinBarNC = { bg = c.bg },
   WinSeparator = { fg = c.gray6, bg = c.bg },

   -- Float
   NormalFloat = { fg = c.gray11, bg = c.menu_bg },
   NormalFloatBorder = { fg = c.gray8, bg = c.menu_bg },
   FloatBorder = { fg = c.gray8, bg = c.menu_bg },

   -- Pmenu / WildMenu
   Pmenu = { link = '', fg = c.gray11, bg = c.menu_bg },
   PmenuSel = { fg = nil, bg = c.ui5_blue },
   PmenuSbar = { fg = nil, bg = c.ui5_blue },
   PmenuThumb = { fg = nil, bg = c.ui5_blue },
   PmenuKind = { fg = c.gray11, bg = c.menu_bg },
   PmenuExtra = { fg = c.gray11, bg = c.menu_bg },
   WildMenu = { fg = c.fg, bg = c.ui5_blue },
   QuickFixLine = { fg = nil, bg = c.ui7_blue },

   -- Buffer
   BufferCurrent = { fg = c.fg, bg = c.bg },
   BufferCurrentIndex = { fg = c.fg, bg = c.bg },
   BufferCurrentMod = { fg = c.info, bg = c.bg },
   BufferCurrentSign = { fg = c.hint, bg = c.bg },
   BufferCurrentTarget = { fg = c.red, bg = c.bg, bold = true },
   BufferVisible = { fg = c.fg, bg = c.bg },
   BufferVisibleIndex = { fg = c.fg, bg = c.bg },
   BufferVisibleMod = { fg = c.info, bg = c.bg },
   BufferVisibleSign = { fg = c.gray, bg = c.bg },
   BufferVisibleTarget = { fg = c.red, bg = c.bg, bold = true },
   BufferInactive = { fg = c.gray, bg = c.alt_bg },
   BufferInactiveIndex = { fg = c.gray, bg = c.alt_bg },
   BufferInactiveMod = { fg = c.info, bg = c.alt_bg },
   BufferInactiveSign = { fg = c.gray, bg = c.alt_bg },
   BufferInactiveTarget = { fg = c.red, bg = c.alt_bg, bold = true },

   -- StatusLine
   StatusLine = { fg = c.context, bg = c.alt_bg },
   StatusLineNC = { fg = c.line, bg = c.bg },
   StatusLineSeparator = { fg = c.line, bg = nil },
   StatusLineTerm = { fg = c.line, bg = nil },
   StatusLineTermNC = { fg = c.line, bg = nil },

   -- Scrollbar
   ScrollbarHandle = { bg = c.line },
   -- ScrollbarCursor = { bg = c.line },
   -- ScrollbarSearch = { bg = c.line },
   -- ScrollbarError = { bg = c.line },
   -- ScrollbarWarn = { bg = c.line },
   -- ScrollbarInfo = { bg = c.line },
   -- ScrollbarHint = { bg = c.line },
   -- ScrollbarMisc = { bg = c.line },
   -- ScrollbarError = { bg = c.line },
   -- ScrollbarGitAdd = { bg = c.line },
   -- ScrollbarGitChange = { bg = c.line },
   -- ScrollbarGitDelete = { bg = c.line },

   -- Lsp
   DiagnosticHint = { fg = c.hint, bg = nil },
   DiagnosticInfo = { fg = c.info, bg = nil },
   DiagnosticWarn = { fg = c.warn, bg = nil },
   DiagnosticError = { fg = c.error, bg = nil },
   DiagnosticOther = { fg = c.ui_purple, bg = nil },
   DiagnosticSignHint = { link = 'DiagnosticHint' },
   DiagnosticSignInfo = { link = 'DiagnosticInfo' },
   DiagnosticSignWarn = { link = 'DiagnosticWarn' },
   DiagnosticSignError = { link = 'DiagnosticError' },
   DiagnosticSignOther = { link = 'DiagnosticOther' },
   DiagnosticSignWarning = { link = 'DiagnosticWarn' },
   DiagnosticFloatingHint = { link = 'DiagnosticHint' },
   DiagnosticFloatingInfo = { link = 'DiagnosticInfo' },
   DiagnosticFloatingWarn = { link = 'DiagnosticWarn' },
   DiagnosticFloatingError = { link = 'DiagnosticError' },
   DiagnosticUnderlineHint = { fg = nil, bg = nil, sp = c.hint, undercurl = true },
   DiagnosticUnderlineInfo = { fg = nil, bg = nil, sp = c.info, undercurl = true },
   DiagnosticUnderlineWarn = { fg = nil, bg = nil, sp = c.warn, undercurl = true },
   DiagnosticUnderlineError = { fg = nil, bg = nil, sp = c.error, undercurl = true },
   DiagnosticSignInformation = { link = 'DiagnosticInfo' },
   DiagnosticVirtualTextHint = { fg = c.hint, bg = c.hint_bg },
   DiagnosticVirtualTextInfo = { fg = c.info, bg = c.info_bg },
   DiagnosticVirtualTextWarn = { fg = c.warn, bg = c.warn_bg },
   DiagnosticVirtualTextError = { fg = c.error, bg = c.error_bg },
   LspDiagnosticsError = { fg = c.error, bg = nil },
   LspDiagnosticsWarning = { fg = c.warn, bg = nil },
   LspDiagnosticsInfo = { fg = c.info, bg = nil },
   LspDiagnosticsInformation = { link = 'LspDiagnosticsInfo' },
   LspDiagnosticsHint = { fg = c.hint, bg = nil },
   LspDiagnosticsDefaultError = { link = 'LspDiagnosticsError' },
   LspDiagnosticsDefaultWarning = { link = 'LspDiagnosticsWarning' },
   LspDiagnosticsDefaultInformation = { link = 'LspDiagnosticsInfo' },
   LspDiagnosticsDefaultInfo = { link = 'LspDiagnosticsInfo' },
   LspDiagnosticsDefaultHint = { link = 'LspDiagnosticsHint' },
   LspDiagnosticsVirtualTextError = { link = 'DiagnosticVirtualTextError' },
   LspDiagnosticsVirtualTextWarning = { link = 'DiagnosticVirtualTextWarn' },
   LspDiagnosticsVirtualTextInformation = { link = 'DiagnosticVirtualTextInfo' },
   LspDiagnosticsVirtualTextInfo = { link = 'DiagnosticVirtualTextInfo' },
   LspDiagnosticsVirtualTextHint = { link = 'DiagnosticVirtualTextHint' },
   LspDiagnosticsFloatingError = { link = 'LspDiagnosticsError' },
   LspDiagnosticsFloatingWarning = { link = 'LspDiagnosticsWarning' },
   LspDiagnosticsFloatingInformation = { link = 'LspDiagnosticsInfo' },
   LspDiagnosticsFloatingInfo = { link = 'LspDiagnosticsInfo' },
   LspDiagnosticsFloatingHint = { link = 'LspDiagnosticsHint' },
   LspDiagnosticsSignError = { link = 'LspDiagnosticsError' },
   LspDiagnosticsSignWarning = { link = 'LspDiagnosticsWarning' },
   LspDiagnosticsSignInformation = { link = 'LspDiagnosticsInfo' },
   LspDiagnosticsSignInfo = { link = 'LspDiagnosticsInfo' },
   LspDiagnosticsSignHint = { link = 'LspDiagnosticsHint' },
   NvimTreeLspDiagnosticsError = { link = 'LspDiagnosticsError' },
   NvimTreeLspDiagnosticsWarning = { link = 'LspDiagnosticsWarning' },
   NvimTreeLspDiagnosticsInformation = { link = 'LspDiagnosticsInfo' },
   NvimTreeLspDiagnosticsInfo = { link = 'LspDiagnosticsInfo' },
   NvimTreeLspDiagnosticsHint = { link = 'LspDiagnosticsHint' },
   LspDiagnosticsUnderlineError = { link = 'DiagnosticUnderlineError' },
   LspDiagnosticsUnderlineWarning = { link = 'DiagnosticUnderlineWarn' },
   LspDiagnosticsUnderlineInformation = { link = 'DiagnosticUnderlineInfo' },
   LspDiagnosticsUnderlineInfo = { link = 'DiagnosticUnderlineInfo' },
   LspDiagnosticsUnderlineHint = { link = 'DiagnosticUnderlineHint' },
   LspReferenceRead = { fg = nil, bg = c.reference },
   LspReferenceText = { fg = nil, bg = c.reference },
   LspReferenceWrite = { fg = nil, bg = c.reference },
   IlluminatedWordRead = { link = 'LspReferenceRead' },
   IlluminatedWordText = { link = 'LspReferenceText' },
   IlluminatedWordWrite = { link = 'LspReferenceWrite' },
   LspCodeLens = { fg = c.context, bg = nil, italic = true },
   LspCodeLensSeparator = { fg = c.context, bg = nil, italic = true },

   -- LspInfo
   LspInfo = {},
   LspInfoTip = { link = 'Comment' },
   LspInfoTitle = { link = 'Title' },
   LspInfoList = { link = 'Function' },
   LspInfoFiletype = { link = 'Type' },
   LspInfoFiletypeList = {}, -- cleared
   LspInfoListList = {}, -- cleared
   -- LspInfoBorder = { link = 'Label' },
   LspInfoBorder = { fg = c.gray }, -- "#777777"

   -- Misc
   diffAdded = { fg = c.sign_add, bg = nil },
   diffRemoved = { fg = c.sign_delete, bg = nil },
   diffFileId = { fg = c.blue, bg = nil, bold = true, reverse = true },
   diffFile = { fg = c.alt_bg, bg = nil },
   diffNewFile = { fg = c.green, bg = nil },
   diffOldFile = { fg = c.red, bg = nil },
   debugPc = { fg = nil, bg = c.ui5_blue },
   debugBreakpoint = { fg = c.red, bg = nil, reverse = true },
   CodiVirtualText = { fg = c.hint, bg = nil },
   SniprunVirtualTextOk = { fg = c.hint, bg = nil },
   SniprunFloatingWinOk = { fg = c.hint, bg = nil },
   SniprunVirtualTextErr = { fg = c.error, bg = nil },
   SniprunFloatingWinErr = { fg = c.error, bg = nil },
   DapBreakpoint = { fg = c.error, bg = nil },

   -- Language
   xmlTag = { fg = c.cyan, bg = nil },
   xmlTagName = { fg = c.cyan, bg = nil },
   xmlEndTag = { fg = c.cyan, bg = nil },
   -- yamlPlainScalar = { fg = c.orange, bg = nil },
   -- yamlTSField = { fg = c.blue, bg = nil },
   luaFunc = { fg = c.yellow, bg = nil },
   luaFunction = { fg = c.blue, bg = nil },
   hclTSPunctSpecial = { fg = c.alt_fg, bg = nil },
   htmlH1 = { fg = c.fg, bg = nil },
   htmlH2 = { fg = c.fg, bg = nil },
   htmlH3 = { fg = c.fg, bg = nil },
   htmlH4 = { fg = c.fg, bg = nil },
   htmlH5 = { fg = c.fg, bg = nil },
   htmlH6 = { fg = c.fg, bg = nil },
   htmlHead = { fg = c.fg, bg = nil },
   htmlTitle = { fg = c.fg, bg = nil },
   htmlArg = { fg = c.fg, bg = nil },
   htmlTag = { fg = c.blue, bg = nil },
   htmlTagN = { fg = c.blue, bg = nil },
   htmlTagName = { fg = c.blue, bg = nil },
   htmlComment = { fg = c.green, bg = nil },
   htmlLink = { fg = c.orange, bg = nil, underline = true },
   cssBraces = { fg = c.fg, bg = nil },
   cssInclude = { fg = c.purple, bg = nil },
   cssTagName = { fg = c.yellow, bg = nil },
   cssClassName = { fg = c.yellow, bg = nil },
   cssPseudoClass = { fg = c.yellow, bg = nil },
   cssPseudoClassId = { fg = c.yellow, bg = nil },
   cssPseudoClassLang = { fg = c.yellow, bg = nil },
   cssIdentifier = { fg = c.yellow, bg = nil },
   cssProp = { fg = c.fg, bg = nil },
   cssDefinition = { fg = c.fg, bg = nil },
   cssAttr = { fg = c.orange, bg = nil },
   cssAttrRegion = { fg = c.orange, bg = nil },
   cssColor = { fg = c.orange, bg = nil },
   cssFunction = { fg = c.purple, bg = nil },
   cssFunctionName = { fg = c.yellow, bg = nil },
   cssVendor = { fg = c.orange, bg = nil },
   cssValueNumber = { fg = c.orange, bg = nil },
   cssValueLength = { fg = c.orange, bg = nil },
   cssUnitDecorators = { fg = c.orange, bg = nil },
   cssStyle = { fg = c.fg, bg = nil },
   cssImportant = { fg = c.blue, bg = nil },
   jsonKeyword = { fg = c.blue, bg = nil },
   yamlBlockMappingKey = { fg = c.blue, bg = nil },
   tomlTSProperty = { fg = c.blue, bg = nil },
   zshKSHFunction = { link = 'Function' },
   zshVariableDef = { link = 'Constant' },
}
