local c = require('darkplus.palette')

-- Language
return {
   xmlTag = { fg = c.cyan, bg = nil },
   xmlTagName = { fg = c.cyan, bg = nil },
   xmlEndTag = { fg = c.cyan, bg = nil },
   -- yamlPlainScalar = { fg = c.orange, bg = nil },
   -- yamlTSField = { fg = c.blue, bg = nil },
   luaFunc = { fg = c.yellow, bg = nil },
   luaFunction = { fg = c.blue, bg = nil },
   hclTSPunctSpecial = { fg = c.alt_fg, bg = nil },
   htmlH1 = { fg = c.fg, bg = nil },
   htmlH2 = { fg = c.fg, bg = nil },
   htmlH3 = { fg = c.fg, bg = nil },
   htmlH4 = { fg = c.fg, bg = nil },
   htmlH5 = { fg = c.fg, bg = nil },
   htmlH6 = { fg = c.fg, bg = nil },
   htmlHead = { fg = c.fg, bg = nil },
   htmlTitle = { fg = c.fg, bg = nil },
   htmlArg = { fg = c.fg, bg = nil },
   htmlTag = { fg = c.blue, bg = nil },
   htmlTagN = { fg = c.blue, bg = nil },
   htmlTagName = { fg = c.blue, bg = nil },
   htmlComment = { fg = c.green, bg = nil },
   htmlLink = { fg = c.orange, bg = nil, underline = true },
   cssBraces = { fg = c.fg, bg = nil },
   cssInclude = { fg = c.purple, bg = nil },
   cssTagName = { fg = c.yellow, bg = nil },
   cssClassName = { fg = c.yellow, bg = nil },
   cssPseudoClass = { fg = c.yellow, bg = nil },
   cssPseudoClassId = { fg = c.yellow, bg = nil },
   cssPseudoClassLang = { fg = c.yellow, bg = nil },
   cssIdentifier = { fg = c.yellow, bg = nil },
   cssProp = { fg = c.fg, bg = nil },
   cssDefinition = { fg = c.fg, bg = nil },
   cssAttr = { fg = c.orange, bg = nil },
   cssAttrRegion = { fg = c.orange, bg = nil },
   cssColor = { fg = c.orange, bg = nil },
   cssFunction = { fg = c.purple, bg = nil },
   cssFunctionName = { fg = c.yellow, bg = nil },
   cssVendor = { fg = c.orange, bg = nil },
   cssValueNumber = { fg = c.orange, bg = nil },
   cssValueLength = { fg = c.orange, bg = nil },
   cssUnitDecorators = { fg = c.orange, bg = nil },
   cssStyle = { fg = c.fg, bg = nil },
   cssImportant = { fg = c.blue, bg = nil },
   jsonKeyword = { fg = c.blue, bg = nil },
   yamlBlockMappingKey = { fg = c.blue, bg = nil },
   tomlTSProperty = { fg = c.blue, bg = nil },
   zshKSHFunction = { link = 'Function' },
   zshVariableDef = { link = 'Constant' },
}
