local c = require('darkplus.palette')

-- LSP
return {
   DiagnosticHint = { fg = c.hint, bg = nil },
   DiagnosticInfo = { fg = c.info, bg = nil },
   DiagnosticWarn = { fg = c.warn, bg = nil },
   DiagnosticError = { fg = c.error, bg = nil },
   DiagnosticOther = { fg = c.ui_purple, bg = nil },
   DiagnosticSignHint = { link = 'DiagnosticHint' },
   DiagnosticSignInfo = { link = 'DiagnosticInfo' },
   DiagnosticSignWarn = { link = 'DiagnosticWarn' },
   DiagnosticSignError = { link = 'DiagnosticError' },
   DiagnosticSignOther = { link = 'DiagnosticOther' },
   DiagnosticSignWarning = { link = 'DiagnosticWarn' },
   DiagnosticFloatingHint = { link = 'DiagnosticHint' },
   DiagnosticFloatingInfo = { link = 'DiagnosticInfo' },
   DiagnosticFloatingWarn = { link = 'DiagnosticWarn' },
   DiagnosticFloatingError = { link = 'DiagnosticError' },
   DiagnosticUnderlineHint = { fg = nil, bg = nil, sp = c.hint, undercurl = true },
   DiagnosticUnderlineInfo = { fg = nil, bg = nil, sp = c.info, undercurl = true },
   DiagnosticUnderlineWarn = { fg = nil, bg = nil, sp = c.warn, undercurl = true },
   DiagnosticUnderlineError = { fg = nil, bg = nil, sp = c.error, undercurl = true },
   DiagnosticSignInformation = { link = 'DiagnosticInfo' },
   DiagnosticVirtualTextHint = { fg = c.hint, bg = c.hint_bg },
   DiagnosticVirtualTextInfo = { fg = c.info, bg = c.info_bg },
   DiagnosticVirtualTextWarn = { fg = c.warn, bg = c.warn_bg },
   DiagnosticVirtualTextError = { fg = c.error, bg = c.error_bg },
   LspDiagnosticsError = { fg = c.error, bg = nil },
   LspDiagnosticsWarning = { fg = c.warn, bg = nil },
   LspDiagnosticsInfo = { fg = c.info, bg = nil },
   LspDiagnosticsInformation = { link = 'LspDiagnosticsInfo' },
   LspDiagnosticsHint = { fg = c.hint, bg = nil },
   LspDiagnosticsDefaultError = { link = 'LspDiagnosticsError' },
   LspDiagnosticsDefaultWarning = { link = 'LspDiagnosticsWarning' },
   LspDiagnosticsDefaultInformation = { link = 'LspDiagnosticsInfo' },
   LspDiagnosticsDefaultInfo = { link = 'LspDiagnosticsInfo' },
   LspDiagnosticsDefaultHint = { link = 'LspDiagnosticsHint' },
   LspDiagnosticsVirtualTextError = { link = 'DiagnosticVirtualTextError' },
   LspDiagnosticsVirtualTextWarning = { link = 'DiagnosticVirtualTextWarn' },
   LspDiagnosticsVirtualTextInformation = { link = 'DiagnosticVirtualTextInfo' },
   LspDiagnosticsVirtualTextInfo = { link = 'DiagnosticVirtualTextInfo' },
   LspDiagnosticsVirtualTextHint = { link = 'DiagnosticVirtualTextHint' },
   LspDiagnosticsFloatingError = { link = 'LspDiagnosticsError' },
   LspDiagnosticsFloatingWarning = { link = 'LspDiagnosticsWarning' },
   LspDiagnosticsFloatingInformation = { link = 'LspDiagnosticsInfo' },
   LspDiagnosticsFloatingInfo = { link = 'LspDiagnosticsInfo' },
   LspDiagnosticsFloatingHint = { link = 'LspDiagnosticsHint' },
   LspDiagnosticsSignError = { link = 'LspDiagnosticsError' },
   LspDiagnosticsSignWarning = { link = 'LspDiagnosticsWarning' },
   LspDiagnosticsSignInformation = { link = 'LspDiagnosticsInfo' },
   LspDiagnosticsSignInfo = { link = 'LspDiagnosticsInfo' },
   LspDiagnosticsSignHint = { link = 'LspDiagnosticsHint' },
   NvimTreeLspDiagnosticsError = { link = 'LspDiagnosticsError' },
   NvimTreeLspDiagnosticsWarning = { link = 'LspDiagnosticsWarning' },
   NvimTreeLspDiagnosticsInformation = { link = 'LspDiagnosticsInfo' },
   NvimTreeLspDiagnosticsInfo = { link = 'LspDiagnosticsInfo' },
   NvimTreeLspDiagnosticsHint = { link = 'LspDiagnosticsHint' },
   LspDiagnosticsUnderlineError = { link = 'DiagnosticUnderlineError' },
   LspDiagnosticsUnderlineWarning = { link = 'DiagnosticUnderlineWarn' },
   LspDiagnosticsUnderlineInformation = { link = 'DiagnosticUnderlineInfo' },
   LspDiagnosticsUnderlineInfo = { link = 'DiagnosticUnderlineInfo' },
   LspDiagnosticsUnderlineHint = { link = 'DiagnosticUnderlineHint' },
   LspReferenceRead = { fg = nil, bg = c.reference },
   LspReferenceText = { fg = nil, bg = c.reference },
   LspReferenceWrite = { fg = nil, bg = c.reference },
   IlluminatedWordRead = { link = 'LspReferenceRead' },
   IlluminatedWordText = { link = 'LspReferenceText' },
   IlluminatedWordWrite = { link = 'LspReferenceWrite' },
   LspCodeLens = { fg = c.context, bg = nil, italic = true },
   LspCodeLensSeparator = { fg = c.context, bg = nil, italic = true },

   -- LspInfo
   LspInfo = {},
   LspInfoTip = { link = 'Comment' },
   LspInfoTitle = { link = 'Title' },
   LspInfoList = { link = 'Function' },
   LspInfoFiletype = { link = 'Type' },
   LspInfoFiletypeList = {}, -- cleared
   LspInfoListList = {}, -- cleared
   -- LspInfoBorder = { link = 'Label' },
   LspInfoBorder = { fg = c.gray }, -- "#777777"
}
