local c = require('darkplus.palette')

-- Main
return {
   -- Editor
   Normal = { fg = c.fg, bg = c.bg },
   SignColumn = { fg = nil, bg = nil },
   MsgArea = { fg = c.fg, bg = c.bg },
   ModeMsg = { fg = c.fg, bg = c.alt_bg },
   MsgSeparator = { fg = c.fg, bg = c.bg },
   SpellBad = { fg = nil, bg = nil, sp = c.red, undercurl = true },
   SpellCap = { fg = nil, bg = nil, sp = c.yellow, undercurl = true },
   SpellLocal = { fg = nil, bg = nil, sp = c.green, underline = true },
   SpellRare = { fg = nil, bg = nil, sp = c.purple, underline = true },
   NormalNC = { fg = c.fg, bg = c.bg },
   -- Pmenu
   Pmenu = { link = '', fg = c.gray11, bg = c.menu_bg }, -- fg = c.alt_fg, bg = c.menu_bg
   PmenuSel = { fg = nil, bg = c.ui5_blue },
   PmenuSbar = { fg = nil, bg = c.ui5_blue },
   PmenuThumb = { fg = nil, bg = c.ui5_blue },
   PmenuKind = { fg = c.gray11, bg = c.menu_bg },
   PmenuExtra = { fg = c.gray11, bg = c.menu_bg },

   WildMenu = { fg = c.fg, bg = c.ui5_blue },
   CursorLineNr = { fg = c.light_gray, bg = nil },
   Folded = { fg = c.gray, bg = c.alt_bg },
   FoldColumn = { fg = c.gray, bg = c.alt_bg },
   LineNr = { fg = c.gray, bg = nil },
   Whitespace = { fg = c.dark_gray, bg = nil },
   VertSplit = { fg = c.gray, bg = c.bg },
   CursorLine = { fg = nil, bg = c.alt_bg },
   CursorColumn = { fg = nil, bg = c.alt_bg },
   ColorColumn = { fg = nil, bg = c.alt_bg },
   -- NormalFloat = { fg = "NONE", bg = c.alt_bg },
   FloatBorder = { fg = c.gray8, bg = c.menu_bg },
   NormalFloat = { fg = c.gray11, bg = c.menu_bg }, -- fg = 'NONE, bg = c.bg
   NormalFloatBorder = { fg = c.gray8, bg = c.menu_bg }, -- Custom highlight
   Visual = { fg = nil, bg = c.ui_blue },
   VisualNOS = { fg = nil, bg = c.alt_bg },
   WarningMsg = { fg = c.ui_orange, bg = c.bg },
   DiffText = { bg = c.sign_delete_bg },
   DiffAdd = { bg = c.sign_add_bg },
   DiffChange = { bg = c.sign_change_bg },
   DiffDelete = { bg = c.sign_delete_bg },
   QuickFixLine = { fg = nil, bg = c.ui7_blue },
   MatchWord = { fg = nil, bg = c.reference },
   MatchParen = { fg = c.hint, bg = c.reference },
   MatchWordCur = { fg = nil, bg = c.reference },
   MatchParenCur = { fg = nil, bg = c.reference },
   Cursor = { fg = c.cursor_fg, bg = c.cursor_bg },
   lCursor = { fg = c.cursor_fg, bg = c.cursor_bg },
   CursorIM = { fg = c.cursor_fg, bg = c.cursor_bg },
   TermCursor = { fg = c.cursor_fg, bg = c.cursor_bg },
   TermCursorNC = { fg = c.cursor_fg, bg = c.cursor_bg },
   Conceal = { fg = c.gray, bg = nil },
   Directory = { fg = c.folder_blue, bg = nil },
   SpecialKey = { fg = c.blue, bg = nil, bold = true },
   ErrorMsg = { fg = c.error, bg = c.bg, bold = true },
   Search = { fg = nil, bg = c.ui5_blue },
   IncSearch = { fg = nil, bg = c.ui2_orange },
   Substitute = { fg = nil, bg = c.ui2_orange },
   MoreMsg = { fg = c.orange, bg = nil },
   Question = { fg = c.orange, bg = nil },
   EndOfBuffer = { fg = c.bg, bg = nil },
   NonText = { fg = c.gray8, bg = nil },
   TabLine = { fg = c.light_gray, bg = c.line },
   TabLineSel = { fg = c.fg, bg = c.line },
   TabLineFill = { fg = c.line, bg = c.line },
}
